phanindra/phani/urls.py
from django.contrib import admin
from django.urls import path
from phani import views
from django.conf.urls import url,include

app_name = 'phani'

urlpatterns =[
    path('register/',views.register,name='register'),
    path('other/',views.other,name='other'),
    path('formpage/',views.form_name,name='formpage'),
    path('login/',views.user_login,name='user_login')
    ]

phanindra/phanindra/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from phani import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Uncomment the next line to enable the admin:
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('phani/',include('phani.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phanindra/phani/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

"""
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField()
"""


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profiles_pic',blank=True)

    def __str__(self):
        return self.user.username

phanindra/phani/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from phani.models import User
from phani.models import UserProfileInfo






class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')








class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    text = forms .CharField(widget=forms.Textarea)


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields =  '__all__'

  
      
   

phanindra/phani/views.py
from django.shortcuts import render
from django.http import HttpRequest
from phani import forms
from phani.forms import NewUserForm,UserForm,UserProfileInfoForm
from phani.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
     context_dict = {'text': 'hello world','number':100}
     return render(request,'phani/index.html',context_dict)

@login_required
def special(request):
    return HttpResponse("you are logged in , Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))






def register(request):

     registered = False

     if request.method == 'POST':
         user_form = UserForm(data=request.POST)
         profile_form = UserProfileInfoForm(data=request.POST)

         if user_form.is_valid() and profile_form.is_valid():

             user = user_form.save()
             user.set_password(user.password)
             user.save()

             profile = profile_form.save(commit=False)
             profile.user = user

             if 'profile_pic' in request.FILES:
                    profile.profile_pic = request.FILES['profile_pic']
                    profile.save()

                    registered = True
             else:
                    print(user_form.errors,profile_form.errors)
     else:
         user_form = UserForm()
         profile_form = UserProfileInfoForm()
        
     return render(request,'phani/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

    
def other(request):
     return render(request,'phani/other.html')

def form_name(request):
    form = forms.FormName()


    # this is to print the values to console entered in .html page
    if request.method == 'POST':
       form = forms.FormName(request.POST)
       



       if form.is_valid():
            # do something

            print("validation success")
            print("name:"+form.cleaned_data['name'])
            print("email:"+form.cleaned_data['email'])
            print("text:"+form.cleaned_data['text']) 


    return render(request,'phani/formpage.html',{'forms':form})



def User(request):

    form = NewUserForm()

    if request.method == "POST":
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("error from invalid")

    return render(request,'phani/users.html',{'form':form})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("account not active")
        else:
            print("someone tried to login failed")
            print("username:{} and password{}".format(username,password))
            return HttpResponse("invalid login details")
    else:
        return render(request,'phani/login.html',{})

phanindra/phani/templates/phani/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li ><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
             <li><a class="navbar-link" href="{% url 'phani:other' %}">other</a></li>
             <li><a class="navbar-link" href="{% url 'phani:register' %}">register</a></li>


            {% if user.is_authenticated %}
             <li><a class="navbar-link" href="{% url 'logout' %}">logout</a></li>
            {% else %}
             <li><a class="navbar-link" href="{% url 'phani:user_login' %}">login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
    <div class="container">
        {% block body_block%}

        {% endblock %}
    </div>
</body>
</html>

phanindra/phani/templates/phani/formpage.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>form</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h1>fill out the form</h1>
        <form method="post">
        {{ forms.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary " value="submit"/>
            </form>
         <a href="{% url 'phani:users' %}">form page</a>
        <a href="{% url 'admin:index' %}">admin page</a>
        <a href="{% url 'index' %}">index page</a>


    </div>
</body>
</html>

phanindra/phani/templates/phani/index.html
<!DOCTYPE html>

{% extends "phani/base.html"%}
{%block body_block%}
<div class="jumbotron">
    <h1>welcome to index </h1>
</div>




<!--------this code is example of template tag file------>
{#<h1>{{ text|cut:'hello' }}</h1>#}
{#<h1>{{ number|add:"99" }}</h1>#}
   
{%endblock%}

phanindra/phani/templates/phani/login.html
{%  extends 'phani/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>please login</h1>
    <form action="{% url 'phani:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">username:</label>
        <input type="text" name="username" placeholder="enter username"/>

         <label for="password">password:</label>
        <input type="password" name="password" placeholder="enter password"/>

        <input type="submit" name="" value="login"/> 


    </form>
</div>

{% endblock %}

phanindra/phani/templates/phani/other.html
<!DOCTYPE html>

{% extends "phani/base.html"%}
{%block body_block%}
<h1>welcome to other</h1>
{%endblock%}

phanindra/phani/templates/phani/registration.html
<!DOCTYPE html>

{% extends "phani/base.html"%}
{% load staticfiles %}

{% block body_block%}
<div class="jumbotron">
    {% if registered %}
    <h1>thank u for registering</h1>
    
    {% else %}
    <h1>register here</h1>
    <h3>fill out form</h3>

    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register" />
    </form>
   
    {% endif %}
    

</div>


{% endblock %}

phanindra/phani/templates/phani/users.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>users</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1>please signup here!</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="submit" />
        </form>
        <a href="{% url 'phani:forms' %}">form page</a>
    </div>
</body>
</html>